#@ gradle
[module]
id = "my-module"
group-id = "org.example"
version = "1.2.3"

[kotlin]
# Maybe [module.kotlin] can be better?
version = "1.2.3"
compilerOptions = "-Xenable-opt-in -Xother-option"

[target.jvm]
targetVersion = "11"

# Support catalogs?
# [dependencies.catalog(catalog)] ??
# "org.example.my-dependency" = "inherit" ??

[dependencies]
"org.example.my-dependency" = "1.2.3"
"org.example.my-dependency.2" = { version = "1.2.3", repository = "x" }

[dependencies."repository(x)"]
"org.example.my-dependency.3" = "1.2.3"

[target.jvm.dependencies]
"org.example.my-dependency" = "1.2.3"

# Four dimensions:
# 1. Build tools as backends
# 2. Parsing model
# 3. Languages and platforms and their specific attributes
# 4. Package managers