
tasks:
  apiBuild:
    action: !org.jetbrains.amper.plugins.bcv.kotlinApiBuildTask
      settings: ${pluginSettings}
      inputJar: ${module.jar}
      outputApiFile: ${taskOutputDir}/api.dump

  apiCheck:
    action: !org.jetbrains.amper.plugins.bcv.kotlinApiCompareTask
      moduleName: ${module.name}
      builtApiFile: ${tasks.apiBuild.action.outputApiFile}
      projectApiFile: ${module.rootDir}/${pluginSettings.apiDumpDirectoryName}/${module.name}.api

  apiDump:
    action: !org.jetbrains.amper.plugins.bcv.kotlinApiDumpTask
      builtApiFile: ${tasks.apiBuild.action.outputApiFile}
      projectApiFile: ${tasks.apiCheck.action.projectApiFile}