
tasks:
  produceSources:
    action: !com.example.amper.plugin.produce_sources.produce
      kotlin: ${taskOutputDir}/kotlin
      resources: ${taskOutputDir}/resources
    markOutputsAs:
      - path: ${action.kotlin}
        kind: kotlin-sources
      - path: ${action.resources}
        kind: jvm-resources