# An empty module is a marker for the cli and IDE to treat this folder as a module and offer corresponding functionality.
# Also an empty project means a Kotlin/JVM module with a single binary target
# So just by adding any single file user can create a hello world app.

# todo see QUESTIONS.md#Defaults -- about implicit targets