tasks:
  empty-task:
  empty-task2: !com.example.nonExistentTask
  empty-task2-space: !com.example.nonExistentTask # trailing space
  empty-task3-space:
    action: !com.example.nonExistentTask # trailing space
  empty-task3:
    action: !com.example.nonExistentTask