# No need to speficy the type explicitly, by default we create executable.
# In case of JVM executable means a jar with main class.
# type = "executable"

# By default we use JVM platform.
# Build tool will take the latest and put it  'lock' file.
# [platform.jvm]
# jdk=17

[dependencies]
"ktor:ktor-server"="1.2"

"my.org:my-lib"="0.1" # or we can have a shortcurt for local libraries "my.org:my-lib"=snapshot,
                      #  but need to consider, how it would work in CI scenario, and remote binary cache
