product:
  type: android/app

dependencies:
  - org.jetbrains.compose.foundation:foundation:1.4.1
  - org.jetbrains.compose.material3:material3:1.4.1
  - androidx.activity:activity-compose:1.7.2 # integration compose with activities
  - androidx.appcompat:appcompat:1.6.1 # we need special type of activity

settings:
  compose:
    enabled: true
