modules:
  - sources/amper-backend-test
  - sources/amper-cli-test
  - sources/amper-mobile-test
  - sources/amper-project-test
  - sources/amper-wrapper-test
  - sources/android-integration/android-integration-core
  - sources/android-integration/android-utils
  - sources/android-integration/dependency-resolution-android-extension
  - sources/android-integration/gradle-plugin
  - sources/android-integration/runner
  - sources/build-related/build-unpacked-dist
  - sources/build-related/build-zip-dist
  - sources/build-related/generate-build-properties
  - sources/build-related/tasks
  - sources/cli
  - sources/compose-resources
  - sources/concurrency
  - sources/core
  - sources/core-intellij
  - sources/dependency-resolution
  - sources/frontend-api
  - sources/frontend/dr
  - sources/frontend/plain/amper-psi
  - sources/frontend/plain/parserutil-stub
  - sources/frontend/plain/toml-psi
  - sources/frontend/plain/yaml-psi
  - sources/frontend/schema
  - sources/gradle-e2e-test
  - sources/gradle-integration
  - sources/test-base
