modules:
  - build-sources/build-dist
  - build-sources/build-unpacked-dist
  - build-sources/generate-build-properties
  - build-sources/task-helpers
  - sources/amper-backend-test
  - sources/amper-cli-test
  - sources/amper-mobile-test
  - sources/amper-project-templates
  - sources/amper-project-test
  - sources/amper-wrapper
  - sources/amper-wrapper-test
  - sources/android-integration/android-integration-core
  - sources/android-integration/android-sdk-detector
  - sources/android-integration/dependency-resolution-android-extension
  - sources/android-integration/gradle-plugin
  - sources/android-integration/runner
  - sources/cli
  - sources/core
  - sources/core-intellij
  - sources/dependency-resolution
  - sources/frontend-api
  - sources/frontend/dr
  - sources/frontend/plain/amper-psi
  - sources/frontend/plain/parserutil-stub
  - sources/frontend/plain/toml-psi
  - sources/frontend/plain/yaml-psi
  - sources/frontend/schema
  - sources/gradle-e2e-test
  - sources/gradle-integration
  - sources/junit-listeners
  - sources/libraries/async-processes
  - sources/libraries/compose-resources
  - sources/libraries/concurrency
  - sources/libraries/incremental-cache
  - sources/libraries/nio-filechannels
  - sources/libraries/telemetry
  - sources/libraries/xcode-model-ext
  - sources/test-base
