modules:
  - build-sources/amper-distribution
  - build-sources/generate-build-properties
  - build-sources/generate-template-resources
  - repository-restrictions
  - sources/amper-build-info
  - sources/amper-cli
  - sources/amper-compose-hot-reload-recompiler-extension
  - sources/amper-jdk-provisioning
  - sources/amper-junit-listeners
  - sources/amper-maven-publish
  - sources/amper-problem-reporting
  - sources/amper-project-templates
  - sources/amper-project-templates/amper-project-template-resources
  - sources/amper-wrapper
  - sources/android-integration/amper-android-gradle-api
  - sources/android-integration/amper-android-gradle-plugin
  - sources/android-integration/amper-android-runner
  - sources/android-integration/amper-android-sdk-detector
  - sources/core
  - sources/core-intellij
  - sources/dependency-resolution
  - sources/extensibility/amper-extensibility-api
  - sources/extensibility/amper-extensibility-schema-model
  - sources/extensibility/amper-schema-processing
  - sources/extensibility/amper-schema-processor
  - sources/frontend-api
  - sources/frontend/dr
  - sources/frontend/plain/amper-psi
  - sources/frontend/plain/parserutil-stub
  - sources/frontend/plain/toml-psi
  - sources/frontend/plain/yaml-psi
  - sources/frontend/schema
  - sources/libraries/async-processes
  - sources/libraries/compose-resources
  - sources/libraries/concurrency
  - sources/libraries/incremental-cache
  - sources/libraries/nio-filechannels
  - sources/libraries/stdlib-extended
  - sources/libraries/telemetry
  - sources/libraries/xcode-model-ext
  - sources/test-base
  - sources/test-integration/amper-backend-test
  - sources/test-integration/amper-cli-test
  - sources/test-integration/amper-mobile-test
  - sources/test-integration/amper-wrapper-test

plugins:
  - ./build-sources/amper-distribution
  - ./build-sources/generate-build-properties
  - ./build-sources/generate-template-resources