#@ gradle(ios, android)
[module]
id = "my-module"
group-id = "org.example"
version = "1.2.3"

[dependencies]
"io.github.aakira:napier" = "2.6.1"

# Specify ios specific properties for build.
[target.ios]
# Or maybe `type = "appllication"` will be better?
type = "binary"
sceneDelegateClass = "SceneDelegate"
launchStoryboard = "LaunchScreen"

# Explicit duplication of dependencies for specific targets may be better?
# [target."ios, android".dependencies]

[target.ios.dependencies]
# Here we can excersise in imagining what properties should native dependency should have.
# Like, headers path, sources  path, object files path, etc, flags to linker from this library, etc.
# Here I just used some parameters from https://kotlinlang.org/docs/multiplatform-dsl-reference.html#native-targets
"curl" = { native = true, defFile = "ios/src/defFiles/curl.def", packageName = "curl.api" }

# Dependency, declared using cocoa pods package manager.
"NWLogging" = { version = "1.2.6", package = "cocoa" }

# Or we can write something like below, if we have multiple cocoa pods dependencies.
# [target.ios.dependencies."package(cocoa)"]
# "NWLogging" = "1.2.6"

# Specify android specific properties for build.
[target.android]
applicationId = "me.user.androidApp"
minSdkVersion = 24
targetSdkVersion = 31
versionCode = 1
versionName = "1.0"
# Default will be preferable.
# manifest = "some/path/to/manifest.xml"

[target.android.dependencies]
"com.jakewharton.timber:timber" = "5.0.1"