[[module]]
type="Gradle"
path="gradle-project/gradle.build" # todo actually, it's a multi=module project. What does it mean?

[[module]]
type="Maven"
path="maven-project/pom.xml"

[[module]]
type="Swift Package Manager"