[module]
group = "org.example"
version = "1.2.3"
targets = [ "jvm", "ios" ]

[kotlin]
freeCompilerArgs = [ ]
apiVersion = "1.6"
languageVersion = "1.6"

[dependencies]
common = [
    "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4"
]
jvm = [
    "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.6.4"
]
jvm_ios = [

]