# When the module has only one platform the default module layout is
#  - src/
#  - module.toml

# No need to speficy the type explicitly, by default we create executable
# type = "executable"

# no need to specify koltin and it's version explicitly.
# Build tool will take the latest and put it  'lock' file.
# [kotlin]
# version = 1.7

# platform.native means that we compile for current platform.
#   Or maybe it should be specified esplicitly?
#   Shold we perform cross-compilation for all platforms?
[platform.native] #or [platform.curren]

[dependencies]
# Depend on multi-platform library. Tool will figure out platform-specific version
"kotlin:kotlin-logging"="1.2" # by default we use koltin/java distribution (Maven central)


