{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlin",
    "module": "kotlin-stdlib",
    "version": "1.9.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "13.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-stdlib-1.9.20.jar",
          "url": "kotlin-stdlib-1.9.20.jar",
          "size": 1718949,
          "sha512": "13d18c47934af9a986dc9b30d01ea6fc2dee6a6eaf230913c6f69fa3b0f86e57160e598b46f3edf0887c41801e3f7312a0f9585cc748fdc9ed1265f899a83648",
          "sha256": "28a35bcdff46d864f80f346a617e486284b208d17378c41900dfb1de95a90e6c",
          "sha1": "e58b4816ac517e9cc5df1db051120c63d4cde669",
          "md5": "405681a02b165f82fc680133482b210c"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "13.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-stdlib-1.9.20.jar",
          "url": "kotlin-stdlib-1.9.20.jar",
          "size": 1718949,
          "sha512": "13d18c47934af9a986dc9b30d01ea6fc2dee6a6eaf230913c6f69fa3b0f86e57160e598b46f3edf0887c41801e3f7312a0f9585cc748fdc9ed1265f899a83648",
          "sha256": "28a35bcdff46d864f80f346a617e486284b208d17378c41900dfb1de95a90e6c",
          "sha1": "e58b4816ac517e9cc5df1db051120c63d4cde669",
          "md5": "405681a02b165f82fc680133482b210c"
        }
      ]
    },
    {
      "name": "jvmSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-stdlib-1.9.20-sources.jar",
          "url": "kotlin-stdlib-1.9.20-sources.jar",
          "size": 605464,
          "sha512": "aac7712762f31f34953740080b17900e757de0f4024f0be8913294c27fc9e27f4270e3a440ec686500887a6c0f7aabae50cc4403e638b3a28e5c334a87fcadf7",
          "sha256": "e159eaf9f42fe4792ead7572ed44752753a9f4b006f5a10f5eefd04b13b6a363",
          "sha1": "e986a95d49898518c4e736748455e3eacddb2e7e",
          "md5": "dab0ec0037a3cd0682f9b52b743bbb7f"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-stdlib-1.9.20-all.jar",
          "url": "kotlin-stdlib-1.9.20-all.jar",
          "size": 139935,
          "sha512": "6add65e67139517764adbee01432d06e79489d166cec3ea3530d62318e1a008cc28de37eb16332d9e15208776a84fba5568e5850c46fd93b19ef8cffc47ae5f6",
          "sha256": "cec38bc3302e72a8aaf9cde436b5a9071ee0331e2ad05e84d8bb897334d7e9d4",
          "sha1": "6c69e7b26179394dafd3c90e630ef763b8c1a267",
          "md5": "4468f2ad5cecac0c0c2639699aafcfc1"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-stdlib-1.9.20-common.jar",
          "url": "kotlin-stdlib-1.9.20-common.jar",
          "size": 227385,
          "sha512": "124cc75ebc89fc3a07dc00429ced1fc618896da5f2590bd5a97bd68613359520fc68b9f77dc06a85b4b0e1a2cdeba3b15eb436c0788e2370d40eba96e5c68bff",
          "sha256": "cc1174c1693a242dd6cbc816a527c453e0418494e36c50cdc6578bf40171acdb",
          "sha1": "4c7276a1529397ee6389483a408c57a9c6d4ca7d",
          "md5": "49c4222161afc7b5890e4402978f90ac"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotlin-stdlib-1.9.20-common-sources.jar",
          "url": "kotlin-stdlib-1.9.20-common-sources.jar",
          "size": 342181,
          "sha512": "d16b86657ae9b78a1865e45bb08c022e37f480becf80c43680c13b4b77a2caba95321732f766c8eeac3f7f78c76153cef9a10fb2151d96314d82592624c57cbb",
          "sha256": "05981a21b88bcda3125ec22ab679fa5b6e29ecefcb32999c4847ec2bcfae209d",
          "sha1": "c19640f72bcc9a9ef4f8f0fc3978afe43e6d49b7",
          "md5": "2cda3d8c8ae4d6f20337bf2f98ff2454"
        }
      ]
    },
    {
      "name": "nativeApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.20"
          }
        }
      ]
    },
    {
      "name": "jsApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlin-stdlib-js/1.9.20/kotlin-stdlib-js-1.9.20.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-stdlib-js",
        "version": "1.9.20"
      }
    },
    {
      "name": "jsRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlin-stdlib-js/1.9.20/kotlin-stdlib-js-1.9.20.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-stdlib-js",
        "version": "1.9.20"
      }
    },
    {
      "name": "jsV1ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlin-stdlib-js/1.9.20/kotlin-stdlib-js-1.9.20.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-stdlib-js",
        "version": "1.9.20"
      }
    },
    {
      "name": "jsV1RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlin-stdlib-js/1.9.20/kotlin-stdlib-js-1.9.20.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-stdlib-js",
        "version": "1.9.20"
      }
    },
    {
      "name": "jsSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlin-stdlib-js/1.9.20/kotlin-stdlib-js-1.9.20.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-stdlib-js",
        "version": "1.9.20"
      }
    },
    {
      "name": "wasmJsApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlin-stdlib-wasm-js/1.9.20/kotlin-stdlib-wasm-js-1.9.20.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-stdlib-wasm-js",
        "version": "1.9.20"
      }
    },
    {
      "name": "wasmJsRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlin-stdlib-wasm-js/1.9.20/kotlin-stdlib-wasm-js-1.9.20.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-stdlib-wasm-js",
        "version": "1.9.20"
      }
    },
    {
      "name": "wasmJsSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlin-stdlib-wasm-js/1.9.20/kotlin-stdlib-wasm-js-1.9.20.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-stdlib-wasm-js",
        "version": "1.9.20"
      }
    },
    {
      "name": "wasmWasiApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../kotlin-stdlib-wasm-wasi/1.9.20/kotlin-stdlib-wasm-wasi-1.9.20.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-stdlib-wasm-wasi",
        "version": "1.9.20"
      }
    },
    {
      "name": "wasmWasiRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../kotlin-stdlib-wasm-wasi/1.9.20/kotlin-stdlib-wasm-wasi-1.9.20.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-stdlib-wasm-wasi",
        "version": "1.9.20"
      }
    },
    {
      "name": "wasmWasiSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../kotlin-stdlib-wasm-wasi/1.9.20/kotlin-stdlib-wasm-wasi-1.9.20.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-stdlib-wasm-wasi",
        "version": "1.9.20"
      }
    }
  ]
}