[module]
groupId = "my.example"
version = "1.0.0"

[kotlin.compilerPlugins]
"org.jetbrains.compose.compiler:compiler" = "42"

[target.android]
minSdkVersion = 42
targetSdkVersion = 42
manifest = "manifest.xml"

# And idea of template application
target.android = "defaultAndroid"
# or
[target.desktop]
fromTemplate = "defaultAdroid"

[target.desktop.kotlin]
freeCompilerArgs = [ "--linker-option=some" ]

[target.desktop.dependencies]
# inter project
model = "local"
shared-ui-elements = "local"
# external
"some-binary" = { defFile = "local.def", "compilerOptions" = [ "--link=some" ] }