[target]
platform = "current" # todo see QUESTIONS.md#Defaults
# todo see QUESTIONS.md#Build pipeline

[dependencies]
# Depend on multi-platform library. Tool will figure out platform-specific version
"kotlin:kotlin-logging"="1.2" # by default we use koltin/java distribution (Maven central)


