
[[target]]
platform = "ios"
# test = ... - test target is automatically created for each platform. 
# By default we create a binary
# type = "binary"

[[target]]
platform = "jvm"
# test = ... - test target is automatically created for each platform
# By default we create a binary
# type = "binary"

[dependencies]

# Depend on multi-platform library. Tool will figure out platform-specific version
"kotlin:kotlin-logging"="1.2" # by default we use koltin/java distribution (Maven central)


[test-dependencies.jvm]

# Depend on multi-platform library. Tool will figure out platform-specific version
"kotlin:kotlin-logging"="1.2" # by default we use koltin/java distribution (Maven central)


