# --- phantom tree

# module:
#   configuration: <from module.yaml:settings.<plugin-id>>

# --- real tree
tasks:
  generate-konfig:
    # taskOutputDir: <set automatically>
    action: !org.jetbrains.amper.plugins.buildkonfig.generateKonfig
      config: ${pluginSettings}
      outputDir: ${taskOutputDir}  # can be made default to `${taskOutputDir}`?
    markOutputsAs:
      - path: ${action.outputDir} # physical reference
        kind: kotlin-sources
  
  print-generated-sources:
    action: !org.jetbrains.amper.plugins.buildkonfig.printSources
      directory: ${generate-konfig.action.outputDir}

  hello:
    action: !org.jetbrains.amper.plugins.buildkonfig.hello
      thisClasspath:
        - ../app1