
tasks:
  build:
    action: !com.example.distribution.buildDistribution
      baseClasspath: ${module.classpath}
      settings: ${module.configuration}
      distributionDir: ${taskDir}
      baseJar:
        from: ${module.dependency}