
tasks:
  build:
    action: !com.example.distribution.buildDistribution
      baseClasspath: ${module.runtimeClasspath}
      settings: ${pluginSettings}
      distributionDir: ${taskOutputDir}
      baseJar:
        from: ${module.self}