#@ gradle
[module]
group = "org.example"
version = "1.2.3"

[kotlin]
freeCompilerArgs = [ ]
apiVersion = "1.6"
languageVersion = "1.6"

[dependencies]
"org.jetbrains.kotlinx:kotlinx-coroutines-core" = "1.6.4"

[target.android]
compileSdkVersion = "33"
minSdkVersion = "24"
targetSdkVersion = "33"
sourceCompatibility = "VERSION_1_8"
targetCompatibility = "VERSION_1_8"