# I guess, an empty module is just a marker for the cli and IDE
# to treat this folder as a module and offer corresponding functionality.

# We might want to have model versioning in order to offer some automated assistance
# like compatibility and schema checks, migration etc.
# version/compatibility = 1.1