# I guess, an empty module is just a marker for the cli and IDE
# to treat this folder as a module and offer corresponding functionality.

# We might want to have model versioning in order to offer some automated assistance
# like compatibility and schema checks, migration etc.
# version/compatibility = 1.1


# also an empty project means a Kotlin/JVM module with a single binary target
# so adding source


# todo different defaults for binary (jvm) and library (multi-platform) could be confusing