# By default we create a binary
# type = "binary"

[[target]]
platform = "ios"
# we can crate a special scripting host for kts and pass ENV to shell scipts
[[target.wrappers]]
before-build="...kts" # generae some code
after-build="...kts" # do some other stuff
runner="...kts" # run the binary
test="...kts" # test the binary

[[target]]
platform = "android"
[[target.wrappers]]
#...


