# By default we create a single JVM target # todo see QUESTIONS.md#Defaults
# [target]
# platform = "jvm"
# type = "binary" # By default we create a binary target # todo see QUESTIONS.md#Defaults

#No need to specify koltin and it's version explicitly.
#[kotlin]
#version = 1.7 # if not specified, the build tool will take the latest and put it  'lock' file.

#[java] default settings for the java tool
#jdk=17 # if not specified, the build tool will take the latest and put it  'lock' file.
#sourceVersion=13
#targetVersion=17


[dependencies]
# koltin-stdlib will be added automatically by the tool, based on the [kotlin] and presence of koltin files
#  todo ^ see QUESTIONS.md#Dependencies

# Depend on multi-platform library. Tool will figure out platform-specific version
"kotlin:kotlin-logging"="1.2" # by default we use koltin/java distribution (Maven central)


