product:
  type: lib
  platforms: [jvm, iosX64]

settings:
  ios:
    <![Warning] This setting was only applicable in Gradle-based Amper and is now obsolete: the team ID is managed in the Xcode project.!>teamId<!>: aaa
  <![Warning] Setting 'android' doesn't have any effect on platforms 'jvm' or 'iosX64'. It only applies to 'android'!>android<!>:
    <![Warning] Setting 'applicationId' cannot be applied to product type 'lib'. Supported product types are: android/app!>applicationId<!>: aaa