product:
  type: lib
  platforms:
    - jvm
    - iosX64
    - android

settings@jvm:
  <![Error] This setting can only be used without any @platform qualifier.!>compose<!>:
    enabled: true

settings@android:
  kotlin:
    <![Error] This setting can only be used without any @platform qualifier.!>serialization<!>:
      format: json