product:
  type: lib
  platforms:
    - jvm
    - iosX64
    - android

settings@jvm:
  <![Error] Setting 'compose' can only be used without any @platform qualifier.!>compose<!>:
    enabled: true

settings@android:
  kotlin:
    <![Error] Setting 'serialization' can only be used without any @platform qualifier.!>serialization<!>:
      format: json