product:
  type: lib
  platforms:
    - jvm
    - iosX64
    - android

settings:
  android:
    <![Warning] Setting 'applicationId' cannot be applied to product type 'lib'. Supported product types are: android/app!>applicationId<!>: aaa

settings@android:
  android:
    <![Warning] Setting 'applicationId' cannot be applied to product type 'lib'. Supported product types are: android/app!>applicationId<!>: aaa

settings@jvm:
  <![Warning] Setting 'android' doesn't have any effect on platform 'jvm'. It only applies to 'android'!>android<!>:
    <![Warning] Setting 'applicationId' cannot be applied to product type 'lib'. Supported product types are: android/app!>applicationId<!>: aaa