product:
  type: lib
  platforms:
    - jvm
    - iosX64
    - android

settings:
  android:
    applicationId: aaa

settings@android:
  android:
    applicationId: aaa

settings@jvm:
  <![Warning] This setting cannot be applied to platforms jvm. Supported platforms are: android!>android<!>:
    applicationId: aaa