product:
  type: lib
  platforms:
    - jvm
    - iosX64
    - android

settings:
  android:
    <![Warning] This setting cannot be applied to a product type lib. Supported product types are: android/app!>applicationId<!>: aaa

settings@android:
  android:
    <![Warning] This setting cannot be applied to a product type lib. Supported product types are: android/app!>applicationId<!>: aaa

settings@jvm:
  <![Warning] This setting cannot be applied to platforms jvm. Supported platforms are: android!>android<!>:
    <![Warning] This setting cannot be applied to a product type lib. Supported product types are: android/app!>applicationId<!>: aaa