modules:
  - valid
  - ./does-not-exist
  - ./does/not/exist
  - not-a-dir
  - not-a-module
  - glob-with-no-matches-at-all/*
  - not-a-modul? # matches some dirs, but none with a module.yaml in it
  - broken[syntax
  - broken[z-a]syntax
  - broken[syntax/with/**
  - forbidden/**/recursive
  - ../jvm-default-compiler-settings # out of root
  - ./ # redundant root module
