# Example of explicit gradle-like sources detetction.
[targets]
# I think it can be omitted?
# common = "default"
js = { sources = "src-js", tests = "test-js" }
ios = { sources = "src-ios", tests = "tests-ios" }

[dependencies]
module = "local"
"org.example.dependency" = "1.2.3"

[dependencies.ios]
"org.example.dependency" = "1.2.3"