[kotlin.plugins]
"org.jetbrains.compose.compiler:compiler" = "1.4.0-rc01"

[dependencies]
"org.jetbrains.compose.ui:ui" = "1.3.0-rc05"
"org.jetbrains.compose.foundation:foundation" = "1.3.0-rc05"
"org.jetbrains.compose.material:material" = "1.3.0-rc05"
"org.jetbrains.compose.runtime:runtime" = "1.3.0-rc05"
"org.jetbrains.kotlin:kotlin-test" = "1.8.10"

[target.android]
namespace = "com.example.myapplication"
minSdk = 24
targetSdk = 33

[target.ios]
compilerArgs = [
    "-linker-option", "-framework", "-linker-option", "Metal",
    "-linker-option", "-framework", "-linker-option", "CoreText",
    "-linker-option", "-framework", "-linker-option", "CoreGraphics",
    "-linker-option", "-framework", "-linker-option", "CoreFoundation",
    "-Xdisable-phases=VerifyBitcode"
]
frameworkBaseName = "shared"