/*
 * Copyright 2000-2024 JetBrains s.r.o. and contributors. Use of this source code is governed by the Apache 2.0 license.
 */

package org.jetbrains.amper.tasks.ios

import kotlinx.serialization.Serializable
import org.jetbrains.amper.cli.commands.tools.XCodeIntegrationCommand
import org.jetbrains.amper.frontend.Platform
import org.jetbrains.amper.util.BuildType
import java.nio.file.Path
import kotlin.io.path.div

/**
 * Provides task-agnostic info based on the given ios variant "context".
 * This is shared between command line tool and ios tasks.
 */
class IosConventions(
    private val buildRootPath: Path,
    val moduleName: String,
    val buildType: BuildType,
    val platform: Platform,
) {
    companion object {
        /**
         * the single default Kotlin iOS framework name that is built per ios/app.
         */
        const val KOTLIN_FRAMEWORK_NAME = "KotlinModules.framework"

        const val COMPOSE_RESOURCES_CONTENT_DIR_NAME = "compose-resources"
    }

    @Serializable
    data class BuildOutputDescription(
        /**
         * A path where a built "<name>.app" resides.
         */
        val appPath: String,

        /**
         * Built product bundleID.
         */
        val productBundleId: String,

        /**
         * Whether the app is signed.
         */
        val isSigningEnabled: Boolean,
    )

    /**
     * Generated by the [XCodeIntegrationCommand].
     * Consumed by the [IosBuildTask].
     */
    fun getBuildOutputDescriptionFilePath(): Path =
        getConventionalXcodeIntegrationDirectory() / "output.json"

    /**
     * A task-agnostic path where Amper-linked iOS framework resides.
     */
    fun getAppFrameworkPath(): Path =
        getConventionalXcodeIntegrationDirectory() / "frameworks" / KOTLIN_FRAMEWORK_NAME

    /**
     * A task-agnostic path where Amper-build iOS compose resources directory resides.
     */
    fun getComposeResourcesDirectory(): Path =
        getConventionalXcodeIntegrationDirectory() / COMPOSE_RESOURCES_CONTENT_DIR_NAME

    private fun getConventionalXcodeIntegrationDirectory(): Path =
        buildRootPath / "xci" / moduleName / platform.pretty / buildType.name
}