# in order for lib to be published or used, it must have coordinates.
# todo see QUESTIONS.md#Coordinates -- regarding local dependenceis
id="org.my.my-lib:0.1"
version="0.1"
# or
# groupId="org.my"
# artifactId="my-lib"
# todo see QUESTIONS.md#Coordinates -- regarding schema

[[target]]
platform=["ios", "android", "jvm"] # To enable platform support to the library, add it to the list
# todo see QUESTIONS.md#Targets -- regarding single vs multiple targets for multi-platform libs

[dependencies]
# Depend on multi-platform library. Tool will figure out platform-specific version
"kotlin:kotlin-logging"="1.2" # by default we use koltin/java distribution (Maven central)

[dependencies.ios]
"SPUtility" = { type = "cocoapods", name="SPUtility.framework" }
# todo see QUESTIONS.md#Publishing -- regarding distribution of native dependenceis



