[[target]]
platform = "ios"
# type = "binary" # By default we create a binary

[[target]]
platform = "android"
# type = "binary" # By default we create a binary

[dependencies] #common dependencies
"org.my:my-lib"="current" # todo see QUESTIONS.md#Coordinates -- regarding referencing local dependenceis

