# --- phantom tree

# module:
#   configuration: <from module.yaml:settings.<plugin-id>>

# --- real tree
tasks:
  generate-konfig:
    # taskOutputDir: <set automatically>
    action: !org.jetbrains.amper.plugins.buildkonfig.generateKonfig
      config: ${pluginSettings.config}
      packageName: ${pluginSettings.packageName}
      objectName: ${pluginSettings.objectName}
      visibility: ${pluginSettings.visibility}
      outputDir: ${taskOutputDir}/sources
      baselinePropertiesFile: ${module.rootDir}/${pluginSettings.propertiesFileName}.properties
    markOutputsAs:
      - path: ${action.outputDir} # physical reference
        kind: kotlin-sources
  
  print-generated-sources:
    action: !org.jetbrains.amper.plugins.buildkonfig.printSources
      directory: ${generate-konfig.action.outputDir}

  checkBaseline:
    action: !org.jetbrains.amper.plugins.buildkonfig.checkBaseline
      config: ${pluginSettings.config}
      baselinePropertiesFile: ${generate-konfig.action.baselinePropertiesFile}