
tasks:
  build:
    action: !buildDist
      distribution:
        cliTgz: ${taskDir}/cli.tgz
        wrappersDir: ${taskDir}/wrappers
      cliRuntimeClasspath: ${module.classpath}
      extraClasspaths: ${module.configuration.extraClasspaths}

  buildUnpacked:
    action: !buildUnpackedClasspath
      outputDir: ${taskDir}/dist
      baseClasspath: ${module.classpath}
      extraClasspaths: ${module.configuration.extraClasspaths}

  uploadLocal:
    action: !uploadDist
      distribution: ${tasks.build.action.distribution}
      repository: maven-local

  upload:
    action: !uploadDist
      distribution: ${tasks.build.action.distribution}
      repository: jetbrains-team-amper-maven

  embedClasspathAsResources:
    action: !buildUnpackedClasspath
      outputDir: ${taskDir}
      baseClasspath: ${module.configuration.embedClasspathAsResources.classpath}
      subdirectoryName: ${module.configuration.embedClasspathAsResources.resourceDirName}
      jarListFileName: classpath.txt
    markOutputsAs:
      - path: ${taskDir}
        kind: jvm-resources