
tasks:
  build:
    action: !buildDist
      distribution:
        cliTgz: ${taskOutputDir}/cli.tgz
        wrappersDir: ${taskOutputDir}/wrappers
      cliRuntimeClasspath: ${module.runtimeClasspath}
      extraClasspaths: ${pluginSettings.extraClasspaths}

  buildUnpacked:
    action: !buildUnpackedClasspath
      outputDir: ${taskOutputDir}/dist
      baseClasspath: ${module.runtimeClasspath}
      extraClasspaths: ${pluginSettings.extraClasspaths}

  uploadLocal:
    action: !uploadDist
      distribution: ${tasks.build.action.distribution}
      repository: maven-local

  upload:
    action: !uploadDist
      distribution: ${tasks.build.action.distribution}
      repository: jetbrains-team-amper-maven

  embedClasspathAsResources:
    action: !buildUnpackedClasspath
      outputDir: ${taskOutputDir}
      baseClasspath: ${pluginSettings.embedClasspathAsResources.classpath}
      subdirectoryName: ${pluginSettings.embedClasspathAsResources.resourceDirName}
      jarListFileName: classpath.txt
    markOutputsAs:
      - path: ${taskOutputDir}
        kind: jvm-resources