
tasks:
  build:
    action: !buildDist
      distribution:
        cliTgz: ${taskDir}/cli.tgz
        wrappersDir: ${taskDir}/wrappers
      cliRuntimeClasspath: ${module.classpath}
      settings: ${module.configuration}

  buildUnpacked:
    action: !buildUnpackedClasspath
      targetDir: ${taskDir}/dist
      baseClasspath: ${module.classpath}
      extraClasspaths: ${module.configuration.extraClasspaths}

  uploadLocal:
    action: !uploadDist
      distribution: ${tasks.build.action.distribution}
      repository: maven-local

  upload:
    action: !uploadDist
      distribution: ${tasks.build.action.distribution}
      repository: jetbrains-team-amper-maven