
tasks:
  build:
    action: !buildDist
      distribution:
        cliTgz: ${taskDir}/cli.tgz
        wrappersDir: ${taskDir}/wrappers
      cliRuntimeClasspath: ${module.classpath}
      settings: ${module.configuration}

  upload-local:
    action: !uploadDist
      distribution: ${tasks.build.action.distribution}
      repository: maven-local

  upload:
    action: !uploadDist
      distribution: ${tasks.build.action.distribution}
      repository: jetbrains-team-amper-maven