
tasks:
  provisionThirdPartyComponents:
    action: !provisionThirdPartyComponents
      stagingDir: ${taskOutputDir}/thirdPartyStagingDir
      versions:
        busyboxW32Version: 'FRP-6075-g169694ebd'
      ourLicenseFile: ${project.rootDir}/LICENSE.txt

  build:
    action: !buildDist
      distribution:
        cliTgz: ${taskOutputDir}/cli.tgz
        wrappersDir: ${taskOutputDir}/wrappers
      cliRuntimeClasspath: ${module.runtimeClasspath}
      extraClasspaths: ${pluginSettings.extraClasspaths}
      extraFilteredClasspaths: ${pluginSettings.extraFilteredClasspaths}
      thirdPartyStagingDir: ${provisionThirdPartyComponents.action.stagingDir}

  buildUnpacked:
    action: !buildUnpackedClasspath
      outputDir: ${taskOutputDir}/dist
      baseClasspath: ${module.runtimeClasspath}
      extraClasspaths: ${pluginSettings.extraClasspaths}
      extraFilteredClasspaths: ${pluginSettings.extraFilteredClasspaths}
      thirdPartyStagingDir: ${provisionThirdPartyComponents.action.stagingDir}

  uploadLocal:
    action: !uploadDist
      distribution: ${tasks.build.action.distribution}
      repository: maven-local

  upload:
    action: !uploadDist
      distribution: ${tasks.build.action.distribution}
      repository: jetbrains-team-amper-maven

  embedClasspathAsResources:
    action: !buildUnpackedClasspath
      outputDir: ${taskOutputDir}
      baseClasspath: ${pluginSettings.embedClasspathAsResources.classpath}
      subdirectoryName: ${pluginSettings.embedClasspathAsResources.resourceDirName}
      jarListFileName: classpath.txt

commands:
  - name: uploadAmperDistribution
    performedBy: upload

  - name: uploadAmperDistributionLocal
    performedBy: uploadLocal

generated:
  resources:
    - directory: ${tasks.embedClasspathAsResources.action.outputDir}
