[module]
groupId = "my.example"
version = "1.0.0"

[kotlin.compilerPlugins]
"org.jetbrains.compose.compiler:compiler" = "42"

[target.ios]
iosVersion = 42
entryPoint = "somePoint"
compiler-options = "--optimize-smth"

[target.ios.kotlin]
freeCompilerArgs = [ "--optIn=hello" ]

[target.ios.dependencies]
# inter project
model = "local"
shared-ui-elements = "local"
# external
"org.jetbrains:kotlinx-serialization" = "42"
"some:cocoa" = { type = "cocoa", version = "42" }
"some-compose:theme" = "42"