/*
 * Copyright 2000-2025 JetBrains s.r.o. and contributors. Use of this source code is governed by the Apache 2.0 license.
 */

package org.jetbrains.amper.plugins

import java.nio.file.Path

/**
 * Use to get module [source directories][sourceDirectories] from the module.
 * Takes the source layout option into account.
 *
 * Use [kind] to get different kinds of module sources.
 *
 * Currently, only JVM non-test sources are supported.
 */
@Schema
interface ModuleSources {
    /**
     * Module to get source directories for.
     */
    val from: Dependency.Local

    /**
     * What kind of sources to request.
     */
    val kind: SourcesKind get() = SourcesKind.KotlinJavaSources

    /**
     * `false` if only user sources are to be included with respect to the project layout.
     * `true` if sources generated by other tasks (plugins, KSP, etc.) are also to be included.
     */
    val includeGenerated: Boolean get() = false

    /**
     * Resulting source directories for the [module][from].
     * Not all of them may exist.
     */
    @Provided
    val sourceDirectories: List<Path>
}
