
tasks:
  generateTemplateResources:
    action: !generateTemplateResources
      outputDir: ${taskOutputDir}
      templatesDir: ${module.rootDir}/resources/templates
    markOutputsAs:
      - path: ${taskOutputDir}
        kind: jvm-resources