/*
 * Copyright 2000-2025 JetBrains s.r.o. and contributors. Use of this source code is governed by the Apache 2.0 license.
 */

package org.jetbrains.amper.tasks.ksp

import org.jetbrains.amper.cli.AmperBuildOutputRoot
import org.jetbrains.amper.frontend.Fragment
import org.jetbrains.amper.tasks.artifacts.KotlinJavaSourceDirArtifact
import java.nio.file.Path

/**
 * A special [KotlinJavaSourceDirArtifact] that is generated by Kotlin Symbol Processing.
 */
class KspGeneratedKotlinJavaSourceDirArtifact(
    buildOutputRoot: AmperBuildOutputRoot,
    fragment: Fragment,
    override val conventionPath: Path?,
) : KotlinJavaSourceDirArtifact(
    buildOutputRoot,
    fragment,
)
