[[target]]
platform="ios"
type = "binary" # iosFramework is a binary in a sense that it can't be reused as library in KMP
packaging="Framework" # ios-specific settings


[dependencies]
# Depend on multi-platform library. Tool will figure out platform-specific version
"kotlin:kotlin-logging"="1.2" # by default we use koltin/java distribution (Maven central)

# since there is only one IOS, target we can specify native dependencies in the common section
"SPUtility" = { type = "cocoapods", name="SPUtility.framework" }



