#@ gradle
[module]
group = "org.example"
version = "1.2.3"

[kotlin]
freeCompilerArgs = [ ]
apiVersion = "1.6"
languageVersion = "1.6"

[dependencies]
"org.jetbrains.kotlinx:kotlinx-coroutines-core" = "1.6.4"

[target.jvm.dependencies]
"org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm" = "1.6.4"