# when module has several platform the default layout is
#  - common/
#  - platform1/
#  - platform2/
#  - module.toml

# No need to speficy the type explicitly, by default we create executable
# type = "executable"

[kotlin]
# version=1.7

[platform.ios]
# iosVersion = 15

[platform.android]
# sdkVersion = 17


[dependencies] #common dependencies
"kotlin:kotlin-logging"="1.2" # multi-platform library

[dependencies.ios]
"kotlin:kotlin-ios-support"="2.3" # ios-specific library

[dependencies.android]
"kotlin:kotlin-android-support"="2.3" # android-specific library

[dependencies.ios+android] # don't like qioting hete
"ktor:ktor-core"="2.3"
