# When the module has only one platform the default layout is
#  - src/
#  - module.toml

# No need to speficy the type explicitly, by default we create executable.
# In case of JVM executable means a jar with main class.
# type = "executable"

# By default we use JVM platform.
# Build tool will take the latest and put it  'lock' file.
# [platform.jvm]
# jdk=17
# sourceVersion=13
# targetVersion=17


[dependencies]
"log4j:log4j-common"="1.2" # by default we use koltin/java distribution (Maven central)


