# Example of explicit gradle-like sources detetction.
[targets]
# I think it can be omitted?
# common = "default"
js = { sources = "src-js", tests = "test-js" }

[dependencies]
"org.example.dependency" = "1.2.3"

[dependencies.js]
"org.example.dependency" = "1.2.3"