
tasks:
  some-task:
    action: !com.example.someAction
      boolean1: ${pluginSettings.boolean}
      boolean2: ${pluginSettings.requiredString} # ${pluginSettings.boolean}+true
      requiredString: "prefix-${pluginSettings.requiredString}-${boolean1}"
      nullablePath: ${pluginSettings.path}/${requiredString}
      path: ${pluginSettings}
      nullableInt: ${pluginSettings.nullablePath}
      nested1: ${module}
      nested2: ${pluginSettings.nested.map}
      dependencies:
        - hel:lo/foo
        - one-part
        - foo:bar:12:compile
        - ${markOutputsAs}
        - []
    taskOutputDir: ./hack/ed

module: {}