#!/usr/bin/env bash

#
# Copyright 2000-2025 JetBrains s.r.o. and contributors. Use of this source code is governed by the Apache 2.0 license.
#

# We use the --livereload flag explicitly because of https://github.com/squidfunk/mkdocs-material/issues/8478
docker run --rm -it -p 8000:8000 -v "${PWD}:/docs" hildan/mkdocs-material-with-plugins serve --dev-addr=0.0.0.0:8000 --livereload --strict "$@"